language: python
python:
 - "3.6"
install:
 - pip install requests
 - pip install pycodestyle
script:
 - pycodestyle --count url-to-json/url_to_json.py
 - pycodestyle --count json-to-xml/json_to_xml.py
 - python3 url-to-json/url_to_json.py https://docs.python.org/3/ "(\w{1,7})"
 - python3 json-to-xml/json_to_xml.py dict2.json New_max4.xml -id mx4
 - python3 json-to-xml/unit_test.py	 
if: branch = master
